# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rwMetropolisC <- function(sigma, x0, N) {
    .Call('_sc19011_rwMetropolisC', PACKAGE = 'sc19011', sigma, x0, N)
}

