# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A random walk Metropolis sampler using Rcpp
#' @description Implement a random walk Metropolis sampler for generating the standard Laplace distribution using Rcpp
#' @param N the number of samples
#' @param sigma parameter for produces a normal distribution random sample
#' @param x0  Initial value
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' sigma <- c(.05, .5, 2, 16)
#' x0 <- 25
#' rw1c <- rwMetropolisC(sigma[1], x0, N)
#' }
#' @export
rwMetropolisC <- function(sigma, x0, N) {
    .Call('_sc19011_rwMetropolisC', PACKAGE = 'sc19011', sigma, x0, N)
}

